# Generated by Django 4.1.4 on 2023-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="img",
            field=models.ImageField(upload_to="portfolio/image/"),
        ),
    ]
